# -*- coding: utf-8 -*-
"""
layout.py
---------
Outer HTML shell for the OCP Sizing report.

Phase 4 of the html_reporter.py refactor lifted the shell (DOCTYPE, head,
header bar, nav-tabs, <main> wrapper, footer, closing tags) into this
module. The shell knows nothing about specific tab contents -- it takes
a pre-rendered tabs_content_html string and a pre-rendered
script_body_html string, and assembles them into the final document.

After Phase 5 the caller will build a tabs dict keyed by tab id and we
will consider a data-driven nav-tabs list. For now Phase 4 keeps the
nav-tabs inline (including the 2 conditional entries for recommendations
and checklist) to remain byte-identical with pre-phase output.
"""

from datetime import datetime

from reporters.report_context import ReportContext
from reporters.styles import STYLES


def build_layout(ctx: ReportContext,
                 tabs_content_html: str,
                 script_body_html: str) -> str:
    """Wrap pre-rendered tab content with the full HTML shell."""
    # Re-bind names used inside the shell f-string. This keeps the
    # literal f-string below identical to what was previously in
    # html_reporter.py -- only the surrounding plumbing moved.
    summary = ctx.summary
    include_recommendations = ctx.include_recommendations

    return f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OCP Sizing Calculator - Assessment Report</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Red+Hat+Display:wght@400;500;600;700&family=Red+Hat+Text:wght@400;500&family=Red+Hat+Mono&display=swap" rel="stylesheet">
{STYLES}
</head>
<body>
    <header class="header">
        <div class="header-content">
            <div class="logo-section">
                <div class="logo">
                    <svg viewBox="0 0 24 24" fill="currentColor">
                        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"/>
                    </svg>
                </div>
                <div class="title-section">
                    <h1>OCP Sizing Calculator</h1>
                    <p>Kubernetes to OpenShift Migration Assessment</p>
                </div>
            </div>
            <div class="header-meta">
                <div>Generated: {datetime.now().strftime("%Y-%m-%d %H:%M")}</div>
                <div>{summary.total_nodes} nodes analyzed</div>
            </div>
        </div>
    </header>
    
    <nav class="nav-tabs">
        <div class="nav-tabs-inner">
            <div class="nav-tab active" data-tab="overview">Overview</div>
            <div class="nav-tab" data-tab="nodes">Node Inventory</div>
            <div class="nav-tab" data-tab="efficiency">Efficiency Analysis</div>
            <div class="nav-tab" data-tab="workloads">Workload Distribution</div>
            <div class="nav-tab" data-tab="workload-inventory">Workload Inventory</div>
            {'<div class="nav-tab" data-tab="recommendations">OCP Recommendations</div>' if include_recommendations else ''}
            {'<div class="nav-tab" data-tab="checklist">Migration Checklist</div>' if include_recommendations else ''}
            <div class="nav-tab" data-tab="storage">Persistent Volumes</div>
        </div>
    </nav>
    
    <main class="main-content">
{tabs_content_html}
    </main>
    
    <footer class="footer">
        <p>OCP Sizing Calculator v1.1 | Generated by Red Hat Solution Architecture</p>
        <p>This assessment is based on point-in-time data. Actual requirements may vary based on workload patterns.</p>
    </footer>
    
{script_body_html}
</body>
</html>
'''
